<?php
/**
 * Gutenverse Services Work Process content.
 */
return array(
	'title'      => __( 'Gutenverse Services Work Process', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"elementId":"guten-McDpTa","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center right"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"yposition":{"Desktop":{"point":"","unit":"px"}},"xposition":{"Desktop":{"point":"","unit":"px"}},"color":{"r":255,"g":255,"b":255,"a":1}},"backgroundOverlay":{"type":"default","color":""},"opacity":"0","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"40","left":""}}}} -->
			<div class="section-wrapper" data-id="McDpTa"><script>var topMcDpTa = {"Desktop":{"point":"0","unit":"px"}};var bottomMcDpTa = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-McDpTa layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-bIZ2Bp","margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":""}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-bIZ2Bp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="bIZ2Bp"><script>var topbIZ2Bp = {"Desktop":{"point":"0","unit":"px"}};var bottombIZ2Bp = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-ZO0rTC","textAlign":{"Desktop":"center"},"color":{"r":51,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"48","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"600"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-ZO0rTC animated guten-element-hide desktop-fadeInUp">Our Work Process</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-qnZDZr","alignment":{"Desktop":"center"},"textColor":{"r":68,"g":68,"b":68,"a":1},"typography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"15","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"350","left":"350"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"70","bottom":"0","left":"70"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"150"}} -->
			<div class="guten-element gutenverse-text-editor guten-qnZDZr animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem aperiam</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"elementId":"guten-Gcxu44","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}}} -->
			<div class="section-wrapper" data-id="Gcxu44"><script>var topGcxu44 = {"Desktop":{"point":"0","unit":"px"}};var bottomGcxu44 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-Gcxu44 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"elementId":"guten-P5ViXv","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"0"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-P5ViXv animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="P5ViXv"><script>var topP5ViXv = {"Desktop":{"point":"0","unit":"px"}};var bottomP5ViXv = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-cQ0vFz","imgSrc":{"media":{"imageId":703,"sizes":{"thumbnail":{"height":90,"width":150,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/Arrow-150x90.webp","orientation":"landscape"},"medium":{"height":40,"width":300,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/Arrow-300x40.webp","orientation":"landscape"},"full":{"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/Arrow.webp","height":90,"width":675,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"unit":"%","point":"45"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"hideTablet":true,"hideMobile":true,"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"210","unit":"px"}},"positioningTop":{"Desktop":{"point":"72","unit":"px"}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-cQ0vFz hide-tablet hide-mobile"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( RENOVATER_URI ) . 'assets/img/Arrow.webp" height="90" width="675"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-VCXJr1","textAlign":{"Desktop":"center","Tablet":"center"},"color":{"r":51,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"19","unit":"px"}}},"background":{"type":"default","color":{"r":252,"g":194,"b":54,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"-20","right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"16","bottom":"10","left":"16"}}},"zIndex":{"Desktop":"11"},"positioningType":{"Desktop":"inline"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-VCXJr1">1</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/icon-box {"elementId":"guten-z6wUTI","title":"Consultation Project","description":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant","icon":"gtn gtn-Consultancy-light","iconSize":{"Desktop":"60"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":[]},"containerBackgroundHover":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"iconColor":{"r":252,"g":194,"b":54,"a":1},"iconHoverColor":{"r":51,"g":51,"b":51,"a":1},"iconHoverBgColor":{"r":252,"g":194,"b":54,"a":1},"iconBorder":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"2","color":{"r":252,"g":194,"b":54,"a":1}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}},"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":68,"g":68,"b":68,"a":1},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":[],"Mobile":[]},"descColor":{"r":51,"g":51,"b":51,"a":1},"descTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":""}}}} -->
			<div class="guten-element guten-z6wUTI guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-Consultancy-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Consultation Project</h2><p class="icon-box-description">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":50,"Mobile":null},"elementId":"guten-bNVLwH","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-bNVLwH animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="bNVLwH"><script>var topbNVLwH = {"Desktop":{"point":"0","unit":"px"}};var bottombNVLwH = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-m6aCNO","imgSrc":{"media":{"imageId":703,"sizes":{"thumbnail":{"height":90,"width":150,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/Arrow-150x90.webp","orientation":"landscape"},"medium":{"height":40,"width":300,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/Arrow-300x40.webp","orientation":"landscape"},"full":{"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/Arrow.webp","height":90,"width":675,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"unit":"%","point":"45"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"hideDesktop":false,"hideTablet":true,"hideMobile":true,"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"210","unit":"px"}},"positioningTop":{"Desktop":{"point":"72","unit":"px"}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-m6aCNO hide-tablet hide-mobile"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( RENOVATER_URI ) . 'assets/img/Arrow.webp" height="90" width="675"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-dxmxNb","textAlign":{"Desktop":"center"},"color":{"r":51,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"19","unit":"px"}}},"background":{"type":"default","color":{"r":252,"g":194,"b":54,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"-20","right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"16","bottom":"10","left":"16"}}},"zIndex":{"Desktop":"11"},"positioningType":{"Desktop":"inline"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-dxmxNb">2</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/icon-box {"elementId":"guten-J2Xac4","title":"Project Planing","description":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant","icon":"gtn gtn-Document-Search-light","iconSize":{"Desktop":"60"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":[]},"containerBackgroundHover":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"iconColor":{"r":252,"g":194,"b":54,"a":1},"iconHoverColor":{"r":51,"g":51,"b":51,"a":1},"iconHoverBgColor":{"r":252,"g":194,"b":54,"a":1},"iconBorder":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"2","color":{"r":252,"g":194,"b":54,"a":1}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}},"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":51,"g":51,"b":51,"a":1},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":[],"Mobile":[]},"descColor":{"r":68,"g":68,"b":68,"a":1},"descTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"}} -->
			<div class="guten-element guten-J2Xac4 guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-Document-Search-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Project Planing</h2><p class="icon-box-description">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100,"Mobile":null},"elementId":"guten-Ku3XsM","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Ku3XsM animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Ku3XsM"><script>var topKu3XsM = {"Desktop":{"point":"0","unit":"px"}};var bottomKu3XsM = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-R7EM0J","textAlign":{"Desktop":"center","Tablet":"center"},"color":{"r":51,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"19","unit":"px"}}},"background":{"type":"default","color":{"r":252,"g":194,"b":54,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"-20","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"","right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"16","bottom":"10","left":"16"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"zIndex":{"Desktop":"11"},"positioningType":{"Desktop":"inline"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-R7EM0J">3</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/icon-box {"elementId":"guten-T5ypm3","title":"Execution Project","description":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant","icon":"gtn gtn-Mechanic-light","iconSize":{"Desktop":"60"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":[]},"containerBackgroundHover":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"iconColor":{"r":252,"g":194,"b":54,"a":1},"iconHoverColor":{"r":51,"g":51,"b":51,"a":1},"iconHoverBgColor":{"r":252,"g":194,"b":54,"a":1},"iconBorder":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"2","color":{"r":252,"g":194,"b":54,"a":1}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}},"Mobile":[]},"titleMargin":{"Desktop":{},"Mobile":[]},"titleColor":{"r":51,"g":51,"b":51,"a":1},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":{},"Mobile":[]},"descColor":{"r":68,"g":68,"b":68,"a":1},"descTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"}} -->
			<div class="guten-element guten-T5ypm3 guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-Mechanic-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Execution Project</h2><p class="icon-box-description">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
