<?php
/**
 * Gutenverse About Us 1 content.
 */
return array(
	'title'      => __( 'Gutenverse About Us 1', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"gap":"no","elementId":"guten-byxivr","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"60","bottom":"60"}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10","top":"40","bottom":"40"}}}} -->
			<div class="section-wrapper" data-id="byxivr"><script>var topbyxivr = {"Desktop":{"point":"0","unit":"px"}};var bottombyxivr = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-byxivr layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":45.56,"Tablet":100,"Mobile":null},"elementId":"guten-e7s6oB","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"50","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"50","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-e7s6oB"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="e7s6oB"><script>var tope7s6oB = {"Desktop":{"point":"0","unit":"px"}};var bottome7s6oB = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-ovT8lH","textAlign":{"Mobile":"center"},"color":{"r":51,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":[],"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"right":"70"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}},"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"0"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-ovT8lH animated guten-element-hide desktop-fadeInLeft">Welcome To Renovater Best Construction</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-BbcUsG","alignment":{"Mobile":"center"},"textColor":{"r":68,"g":68,"b":68,"a":1},"typography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"30","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"150"}} -->
			<div class="guten-element gutenverse-text-editor guten-BbcUsG animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo perspiciatis unde omnis.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/icon-list {"elementId":"guten-bo36tw","spaceBetween":{"Desktop":"15","Mobile":""},"alignList":{"Mobile":"flex-start"},"iconColor":{"r":252,"g":194,"b":54,"a":1},"iconSize":{"Desktop":"15","Mobile":""},"textColor":{"r":68,"g":68,"b":68,"a":1},"textIndent":{"Desktop":"10","Mobile":""},"textTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"border":{"radius":{"Mobile":[]}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"10","left":"20"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
			<div class="guten-element guten-icon-list guten-bo36tw animated guten-element-hide desktop-fadeInLeft"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-pqRGKR","margin":{"Mobile":{"unit":"px","dimension":{"left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"left":""}}}} -->
			<div class="guten-element guten-icon-list-item guten-pqRGKR"><a id="guten-pqRGKR"><i class="fas fa-check"></i><span class="list-text ">Voluptatem accusantium doloremque laudantium</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-lsL56L"} -->
			<div class="guten-element guten-icon-list-item guten-lsL56L"><a id="guten-lsL56L"><i class="fas fa-check"></i><span class="list-text ">Inventore veritatis et quasi architecto beatae vitae</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-D3Frit"} -->
			<div class="guten-element guten-icon-list-item guten-D3Frit"><a id="guten-D3Frit"><i class="fas fa-check"></i><span class="list-text ">Perspiciatis unde omnis iste natus error sit voluptatem accusantiu</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->
			
			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-V3ua88"} -->
			<div class="guten-element guten-icon-list-item guten-V3ua88"><a id="guten-V3ua88"><i class="fas fa-check"></i><span class="list-text ">Inventore veritatis et quasi architecto beatae vitae</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-abpOAt","content":"Read More","buttonSize":"lg","alignButton":{"Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"28"}}},"buttonBackground":{"type":"default","color":{"r":252,"g":194,"b":54,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":51,"g":51,"b":51,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"1300"},"color":{"r":51,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"500"},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-abpOAt"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-lg" href="#"><span>Read More</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":27.42,"Tablet":50,"Mobile":null},"elementId":"guten-mLj5xy","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"left":"0","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"hideMobile":true} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-mLj5xy hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="mLj5xy"><script>var topmLj5xy = {"Desktop":{"point":"0","unit":"px"}};var bottommLj5xy = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-pilCbC","imgSrc":{"media":{"imageId":227,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/iphone-mobile-person-model-spring-phone-513213-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":201,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/iphone-mobile-person-model-spring-phone-513213-pxhere.com-201x300.webp","orientation":"portrait"},"large":{"height":1024,"width":686,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/iphone-mobile-person-model-spring-phone-513213-pxhere.com-686x1024.webp","orientation":"portrait"},"full":{"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/iphone-mobile-person-model-spring-phone-513213-pxhere.com.webp","height":2000,"width":1339,"orientation":"portrait"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Mobile":[]}},"imageFit":{"Desktop":"default"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"0"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-pilCbC animated guten-element-hide desktop-fadeInUp"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( RENOVATER_URI ) . 'assets/img/iphone-mobile-person-model-spring-phone-513213-pxhere.com.webp" height="2000" width="1339"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/fun-fact {"elementId":"guten-WbhhES","iconType":"none","icon":"","iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"prefix":"","number":"20","suffix":"+","title":"Years Experience","superTop":{"Desktop":""},"superSpace":{"Desktop":""},"numberColor":{"Desktop":{"r":3,"g":3,"b":1,"a":1}},"titleColor":{"Desktop":[]},"numberTypography":{"size":{"Desktop":{"point":"28","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"titleTypography":{"lineHeight":{"Desktop":{"point":"","unit":"px"}}},"numberBottomSpace":{"Desktop":""},"titleBottomSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"background":{"type":"default","color":{"r":252,"g":194,"b":54,"a":1}},"border":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"20","color":{"r":255,"g":255,"b":255,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-80","right":"40","bottom":"0","left":"40"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"150"}} -->
			<div class="guten-element guten-WbhhES animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="20" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Years Experience</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":27.01,"Tablet":50,"Mobile":null},"elementId":"guten-8bLC4o","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"bottom left"},"size":{"Desktop":"cover"},"repeat":{"Desktop":"default"}},"verticalAlign":{"Desktop":"default"},"horizontalAlign":{"Desktop":"flex-end"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"},"hideMobile":true} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-8bLC4o animated guten-element-hide desktop-fadeInUp hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="8bLC4o"><script>var top8bLC4o = {"Desktop":{"point":"0","unit":"px"}};var bottom8bLC4o = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon {"elementId":"guten-0mQFpu","icon":"gtn gtn-play-button-light","iconAlign":{"Desktop":"right"},"iconColorOne":{"r":252,"g":194,"b":54,"a":1},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"15"},"iconColorTwo":{"r":51,"g":51,"b":51,"a":1},"iconColorHoverOne":{"r":68,"g":68,"b":68,"a":1},"iconColorHoverTwo":{"r":255,"g":255,"b":255,"a":1},"iconShape":"square","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"all":{"type":"solid","width":"20","color":{"r":255,"g":255,"b":255,"a":1}},"right":{"type":"none"},"top":{"type":"none"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-80"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"zIndex":{"Desktop":"21"},"positioningType":{"Desktop":"inline"}} -->
			<div class="wp-block-gutenverse-icon guten-element guten-0mQFpu guten-icon"><span class="guten-icon-wrapper square stacked"><i class="gtn gtn-play-button-light"></i></span></div>
			<!-- /wp:gutenverse/icon -->
			
			<!-- wp:gutenverse/image {"elementId":"guten-lguQ9y","imgSrc":{"media":{"imageId":230,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/ground-asphalt-construction-truck-vehicle-equipment-1132531-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":200,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/ground-asphalt-construction-truck-vehicle-equipment-1132531-pxhere.com-200x300.webp","orientation":"portrait"},"large":{"height":1024,"width":682,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/ground-asphalt-construction-truck-vehicle-equipment-1132531-pxhere.com-682x1024.webp","orientation":"portrait"},"full":{"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/ground-asphalt-construction-truck-vehicle-equipment-1132531-pxhere.com.webp","height":2560,"width":1706,"orientation":"portrait"}}},"size":"full"},"captionOriginal":"","imgBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-lguQ9y"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( RENOVATER_URI ) . 'assets/img/ground-asphalt-construction-truck-vehicle-equipment-1132531-pxhere.com.webp" height="2560" width="1706"/></a></div>
			<!-- /wp:gutenverse/image --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
