<?php
/**
 * Gutenverse Home Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"gap":"no","elementId":"guten-4qr4Df","background":{"type":"default","image":{"Desktop":{"id":180,"image":"' . esc_url( RENOVATER_URI ) . 'assets/img/safety-health-worker-engineer-construction-industry-1575605-pxhere.com.webp"}},"position":{"Desktop":"center right","Tablet":"center left"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"size":{"Desktop":"cover","Tablet":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1},"gradientColor":[{"color":"rgb(247, 248, 248)","active":false,"opacity":0.53,"id":1,"offset":"0.000"},{"color":"rgb(250, 250, 250)","active":false,"opacity":0,"id":4,"offset":"1.000"}],"gradientType":"linear","gradientAngle":270},"opacity":"0.2","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"200","bottom":"160","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"50","right":"10","left":"10"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="4qr4Df"><script>var top4qr4Df = {"Desktop":{"point":"0","unit":"px"}};var bottom4qr4Df = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-4qr4Df layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-ejE6jy","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-ejE6jy"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ejE6jy"><script>var topejE6jy = {"Desktop":{"point":"0","unit":"px"}};var bottomejE6jy = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-8nzTzc","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}}} -->
			<div class="section-wrapper" data-id="8nzTzc"><script>var top8nzTzc = {"Desktop":{"point":"0","unit":"px"}};var bottom8nzTzc = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-8nzTzc layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":65,"Mobile":null},"elementId":"guten-jaZJOI","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"25","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"60","bottom":"70","left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"50","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"40","left":"20"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"fast","delay":"0"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-jaZJOI animated guten-element-hide fast desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="jaZJOI"><script>var topjaZJOI = {"Desktop":{"point":"0","unit":"px"}};var bottomjaZJOI = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-VEFAkl","color":{"r":252,"g":194,"b":54,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"56","unit":"px"},"Tablet":{"point":"42","unit":"px"},"Mobile":{"point":"28","unit":"px"}},"weight":"700"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"5","left":""}}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-VEFAkl">Building The Future</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/heading {"elementId":"guten-0x6SGd","color":{"r":51,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"56","unit":"px"},"Tablet":{"point":"42","unit":"px"},"Mobile":{"point":"28","unit":"px"}},"weight":"700"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"15","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-0x6SGd">Restoring The Past</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-lDMa5Z","textColor":{"r":68,"g":68,"b":68,"a":1},"typography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300"},"margin":{"Tablet":{"unit":"px","dimension":{"right":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"right":"40","left":""}}},"hideMobile":true} -->
			<div class="guten-element gutenverse-text-editor guten-lDMa5Z hide-mobile"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudanti totam rem aperiam&nbsp;</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":35},"elementId":"guten-6RAHjM"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-6RAHjM"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="6RAHjM"><script>var top6RAHjM = {"Desktop":{"point":"0","unit":"px"}};var bottom6RAHjM = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-EfY2b3","content":"Contact Us","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}}},"buttonBackground":{"type":"default","color":{"r":252,"g":194,"b":54,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":51,"g":51,"b":51,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"-30","right":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"left":"","right":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"60","top":"0","right":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"left":"40"}},"Mobile":{"unit":"px","dimension":{"left":"20"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"500"},"color":{"r":51,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"500"},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-EfY2b3"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>Contact Us</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
