<?php
/**
 * Gutenverse Pricing Fun Fact content.
 */
return array(
	'title'      => __( 'Gutenverse Pricing Fun Fact', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"elementId":"guten-oWqYRw","background":{"type":"default","image":{"Desktop":{"id":552,"image":"' . esc_url( RENOVATER_URI ) . 'assets/img/man-working-sky-roof-wall-asphalt-1139579-pxhere.com.webp"}},"position":{"Desktop":"center right"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(239, 170, 6, 1)","opacity":1,"active":true,"id":1,"offset":"0.161"},{"color":"rgba(0, 0, 0, 0.71)","active":false,"opacity":0.71,"id":2,"offset":"0.161"}],"gradientType":"linear","gradientAngle":"300"},"opacity":"","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"50","top":"50"}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10","top":"30","bottom":"30"}}}} -->
			<div class="section-wrapper" data-id="oWqYRw"><script>var topoWqYRw = {"Desktop":{"point":"0","unit":"px"}};var bottomoWqYRw = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-oWqYRw layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":56.01,"Tablet":100},"elementId":"guten-75yNg3","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-75yNg3"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="75yNg3"><script>var top75yNg3 = {"Desktop":{"point":"0","unit":"px"}};var bottom75yNg3 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-AM8iTQ","textAlign":{"Mobile":"center","Tablet":"left"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"600"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"0"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-AM8iTQ animated guten-element-hide desktop-fadeInLeft">Awesome Facts</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-g4OPER","alignment":{"Mobile":"center","Tablet":"left"},"typography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"60","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"delay":"80","duration":"normal"}} -->
			<div class="guten-element gutenverse-text-editor guten-g4OPER animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph {"textColor":"white"} -->
			<p class="has-white-color has-text-color">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo perspiciatis unde omnis iste.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-8IuRDt","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"140","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="section-wrapper" data-id="8IuRDt"><script>var top8IuRDt = {"Desktop":{"point":"0","unit":"px"}};var bottom8IuRDt = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-8IuRDt layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-RS5gRd","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"0"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-RS5gRd"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="RS5gRd"><script>var topRS5gRd = {"Desktop":{"point":"0","unit":"px"}};var bottomRS5gRd = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-MyeWwR","icon":"gtn gtn-deal-light","iconColor":{"Desktop":{"r":252,"g":194,"b":54,"a":1}},"iconBorder":{"radius":{"Desktop":[],"Tablet":[]}},"iconSize":{"Desktop":"","Tablet":""},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"prefix":"","number":"200","suffix":"+","title":"Completed Projects","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"numberBottomSpace":{"Desktop":""},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"0"}} -->
			<div class="guten-element guten-MyeWwR animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-deal-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="200" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Completed Projects</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"elementId":"guten-pJFDYb","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"80"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-pJFDYb"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="pJFDYb"><script>var toppJFDYb = {"Desktop":{"point":"0","unit":"px"}};var bottompJFDYb = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-jyDUC2","icon":"gtn gtn-User-light","iconColor":{"Desktop":{"r":252,"g":194,"b":54,"a":1}},"iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"prefix":"","number":"300","suffix":"+","title":"Happy Client","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"contentPadding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"30","left":"30","top":"","bottom":""}}},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"80"}} -->
			<div class="guten-element guten-jyDUC2 animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-User-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="300" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Happy Client</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"elementId":"guten-dFf2wr","animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-dFf2wr"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="dFf2wr"><script>var topdFf2wr = {"Desktop":{"point":"0","unit":"px"}};var bottomdFf2wr = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-9oxczF","icon":"gtn gtn-team-2-line","iconColor":{"Desktop":{"r":252,"g":194,"b":54,"a":1}},"iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"prefix":"","number":"128","suffix":"","title":"Professional Team","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"contentPadding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"160"}} -->
			<div class="guten-element guten-9oxczF animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-team-2-line"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="128" data-duration="3500"></span><span class="suffix"></span></div><span class="title">Professional Team</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"elementId":"guten-eJ4S9t","animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"320"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-eJ4S9t"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="eJ4S9t"><script>var topeJ4S9t = {"Desktop":{"point":"0","unit":"px"}};var bottomeJ4S9t = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-lcxx0g","icon":"gtn gtn-trophy-light","iconColor":{"Desktop":{"r":252,"g":194,"b":54,"a":1}},"iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"prefix":"","number":"110","suffix":"","title":"Awards Winning","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"contentPadding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"30","left":"30"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"240"}} -->
			<div class="guten-element guten-lcxx0g animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-trophy-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="110" data-duration="3500"></span><span class="suffix"></span></div><span class="title">Awards Winning</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":43.99,"Tablet":30,"Mobile":null},"elementId":"guten-27g5c6","margin":{"Mobile":[]},"padding":{"Mobile":[]},"hideTablet":true,"hideMobile":true} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-27g5c6 hide-tablet hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="27g5c6"><script>var top27g5c6 = {"Desktop":{"point":"0","unit":"px"}};var bottom27g5c6 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
