<?php
/**
 * Gutenverse Footer content.
 */
return array(
	'title'      => __( 'Gutenverse Footer', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"gap":"no","elementId":"guten-Xu0yaA","background":{"type":"default","color":{"r":19,"g":19,"b":19,"a":1}},"margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"70","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"40","bottom":"20"}}}} -->
            <div class="section-wrapper" data-id="Xu0yaA"><script>var topXu0yaA = {"Desktop":{"point":"0","unit":"px"}};var bottomXu0yaA = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-Xu0yaA layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-WdiwVd","border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-WdiwVd"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="WdiwVd"><script>var topWdiwVd = {"Desktop":{"point":"0","unit":"px"}};var bottomWdiwVd = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-gwjmu4","border":{"radius":{"Desktop":{}},"bottom":{"type":"solid","width":"1","color":{"r":234,"g":234,"b":234,"a":0.1}}},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}}} -->
            <div class="section-wrapper" data-id="gwjmu4"><script>var topgwjmu4 = {"Desktop":{"point":"0","unit":"px"}};var bottomgwjmu4 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-gwjmu4 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":100,"Mobile":null},"elementId":"guten-i0c5Ue","horizontalAlign":{"Desktop":"default","Tablet":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"25","top":"","right":"","left":""}},"Mobile":{}},"padding":{"Tablet":{},"Mobile":{"unit":"px","dimension":{"right":"","left":""}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-i0c5Ue"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="i0c5Ue"><script>var topi0c5Ue = {"Desktop":{"point":"0","unit":"px"}};var bottomi0c5Ue = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-mF4ydt","imgSrc":{"media":{"imageId":1804,"sizes":{"thumbnail":{"height":81,"width":150,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-renovater-2-150x81.webp","orientation":"landscape"},"medium":{"height":41,"width":300,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-renovater-2-300x41.webp","orientation":"landscape"},"full":{"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-renovater-2.webp","height":81,"width":596,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","imgBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"align":{"Tablet":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"100","top":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{"unit":"%","dimension":{"top":"","right":"30","bottom":"","left":"30"}},"Mobile":{"unit":"px","dimension":{"right":"40","left":"40"}}}} -->
            <div class="wp-block-gutenverse-image guten-element guten-image guten-mF4ydt"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( RENOVATER_URI ) . 'assets/img/logo-renovater-2.webp" height="81" width="596"/></a></div>
            <!-- /wp:gutenverse/image --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":33,"Mobile":null},"elementId":"guten-a431Ly","margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}},"Tablet":{}},"padding":{"Desktop":{},"Mobile":{},"Tablet":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-a431Ly"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="a431Ly"><script>var topa431Ly = {"Desktop":{"point":"0","unit":"px"}};var bottoma431Ly = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-ybplqL","title":"Phone","description":"(+021) 645 863 232","icon":"fas fa-phone-alt","iconSize":{"Desktop":"30","Tablet":"25"},"iconPosition":"left","align":{"Desktop":"flex-start","Mobile":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"containerBorder":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"5","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"iconColor":{"r":252,"g":194,"b":54,"a":1},"iconBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"titlePadding":{"Desktop":{},"Tablet":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"5"}},"Tablet":{}},"titleColor":{"r":252,"g":194,"b":54,"a":1},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"","unit":"px"}}},"descMargin":{"Desktop":{},"Tablet":{}},"descColor":{"r":255,"g":255,"b":255,"a":1},"descTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{},"Tablet":{}}} -->
            <div class="guten-element guten-ybplqL guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="fas fa-phone-alt"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Phone</h2><p class="icon-box-description">(+021) 645 863 232</p></div></div></div>
            <!-- /wp:gutenverse/icon-box --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":33,"Mobile":null},"elementId":"guten-5EE2oB","margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"bottom":"5","top":"0","right":"0","left":"0"}},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{},"Tablet":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-5EE2oB"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="5EE2oB"><script>var top5EE2oB = {"Desktop":{"point":"0","unit":"px"}};var bottom5EE2oB = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-Mzdx3s","title":"Mail","description":"support@domain.com","icon":"fas fa-envelope","iconSize":{"Desktop":"30","Tablet":"25"},"iconPosition":"left","align":{"Desktop":"flex-start","Mobile":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"5","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"0","left":"0"}}},"iconColor":{"r":252,"g":194,"b":54,"a":1},"iconBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"titlePadding":{"Desktop":{},"Tablet":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"5"}},"Tablet":{}},"titleColor":{"r":252,"g":194,"b":54,"a":1},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}}},"descMargin":{"Desktop":{},"Tablet":{}},"descColor":{"r":255,"g":255,"b":255,"a":1},"descTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
            <div class="guten-element guten-Mzdx3s guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="fas fa-envelope"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Mail</h2><p class="icon-box-description">support@domain.com</p></div></div></div>
            <!-- /wp:gutenverse/icon-box --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":34,"Mobile":null},"elementId":"guten-LCjpzt","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"5"}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-LCjpzt"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LCjpzt"><script>var topLCjpzt = {"Desktop":{"point":"0","unit":"px"}};var bottomLCjpzt = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-fe4jGh","title":"Location","description":"776 Green Hill Street Elmont","icon":"fas fa-map-marker-alt","iconSize":{"Desktop":"30","Tablet":"25"},"iconPosition":"left","align":{"Desktop":"flex-start","Mobile":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"5","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":""}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"iconColor":{"r":252,"g":194,"b":54,"a":1},"iconBorder":{"radius":{"Desktop":{},"Tablet":{},"Mobile":{}}},"titlePadding":{"Desktop":{},"Tablet":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"5"}},"Tablet":{}},"titleColor":{"r":252,"g":194,"b":54,"a":1},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}}},"descMargin":{"Desktop":{},"Tablet":{}},"descColor":{"r":255,"g":255,"b":255,"a":1},"descTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"left":"","right":""}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
            <div class="guten-element guten-fe4jGh guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="fas fa-map-marker-alt"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Location</h2><p class="icon-box-description">776 Green Hill Street Elmont</p></div></div></div>
            <!-- /wp:gutenverse/icon-box --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->
            
            <!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-IF3V2J","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"40"}}},"padding":{"Desktop":{}}} -->
            <div class="section-wrapper" data-id="IF3V2J"><script>var topIF3V2J = {"Desktop":{"point":"0","unit":"px"}};var bottomIF3V2J = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-IF3V2J layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":38},"elementId":"guten-vln4NZ","margin":{"Desktop":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"40","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-vln4NZ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vln4NZ"><script>var topvln4NZ = {"Desktop":{"point":"0","unit":"px"}};var bottomvln4NZ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-ULQLkr","color":{"r":255,"g":255,"b":255,"a":1},"typography":{"size":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"font":{"label":"Roboto","value":"Roboto","type":"google"},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-ULQLkr">About Us</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-9ogHXR","textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element gutenverse-text-editor guten-9ogHXR"><div class="text-content-inner"><!-- wp:paragraph {"textColor":"white"} -->
            <p class="has-white-color has-text-color">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudanti totam rem aperiam inventore veritatis</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/social-icons {"elementId":"guten-ZH0MUl","iconSize":{"Desktop":{"point":"15","unit":"px"}},"gap":{"Desktop":"20"},"alignment":{"Desktop":"flex-start"},"shape":"circle","iconColor":{"r":19,"g":19,"b":19,"a":1},"bgColor":{"r":252,"g":194,"b":54,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"itemPadding":{"Desktop":{}}} -->
            <div class="guten-element guten-social-icons guten-ZH0MUl circle horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-NbcruZ","iconColor":{"r":51,"g":51,"b":51,"a":1},"bgColor":{"r":252,"g":194,"b":54,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":68,"g":68,"b":68,"a":1}} -->
            <div class="guten-element guten-social-icon guten-NbcruZ facebook"><a id="guten-NbcruZ"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-AQlkDa","iconColor":{"r":51,"g":51,"b":51,"a":1},"bgColor":{"r":252,"g":194,"b":54,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":68,"g":68,"b":68,"a":1}} -->
            <div class="guten-element guten-social-icon guten-AQlkDa twitter"><a id="guten-AQlkDa"><i class="gtn gtn-twitter-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-cWEWHd","iconColor":{"r":51,"g":51,"b":51,"a":1},"bgColor":{"r":252,"g":194,"b":54,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":68,"g":68,"b":68,"a":1}} -->
            <div class="guten-element guten-social-icon guten-cWEWHd instagram"><a id="guten-cWEWHd"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-Xv0CTu","iconColor":{"r":51,"g":51,"b":51,"a":1},"bgColor":{"r":252,"g":194,"b":54,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":68,"g":68,"b":68,"a":1}} -->
            <div class="guten-element guten-social-icon guten-Xv0CTu pinterest"><a id="guten-Xv0CTu"><i class="gtn gtn-pinterest-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":33,"Mobile":null},"elementId":"guten-qzm8AT","margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-qzm8AT"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="qzm8AT"><script>var topqzm8AT = {"Desktop":{"point":"0","unit":"px"}};var bottomqzm8AT = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-UEt8Xj","color":{"r":255,"g":255,"b":255,"a":1},"typography":{"size":{"Desktop":{"point":"20","unit":"px"}},"font":{"label":"Roboto","value":"Roboto","type":"google"},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-UEt8Xj">Quick Links</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/icon-list {"elementId":"guten-pbE1u5","spaceBetween":{"Desktop":"10"},"iconColor":{"r":252,"g":194,"b":54,"a":1},"textColor":{"r":255,"g":255,"b":255,"a":1},"textIndent":{"Desktop":"15"},"textTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300"}} -->
            <div class="guten-element guten-icon-list guten-pbE1u5"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-wYrSzn"} -->
            <div class="guten-element guten-icon-list-item guten-wYrSzn"><a id="guten-wYrSzn"><i class="fas fa-angle-right"></i><span class="list-text ">About Us</span></a></div>
            <!-- /wp:gutenverse/icon-list-item -->
            
            <!-- wp:gutenverse/icon-list-item {"elementId":"guten-UANHs8"} -->
            <div class="guten-element guten-icon-list-item guten-UANHs8"><a id="guten-UANHs8"><i class="fas fa-angle-right"></i><span class="list-text ">Services</span></a></div>
            <!-- /wp:gutenverse/icon-list-item -->
            
            <!-- wp:gutenverse/icon-list-item {"elementId":"guten-FXmR3A"} -->
            <div class="guten-element guten-icon-list-item guten-FXmR3A"><a id="guten-FXmR3A"><i class="fas fa-angle-right"></i><span class="list-text ">Projects</span></a></div>
            <!-- /wp:gutenverse/icon-list-item -->
            
            <!-- wp:gutenverse/icon-list-item {"elementId":"guten-vFxnhu"} -->
            <div class="guten-element guten-icon-list-item guten-vFxnhu"><a id="guten-vFxnhu"><i class="fas fa-angle-right"></i><span class="list-text ">Contact</span></a></div>
            <!-- /wp:gutenverse/icon-list-item --></div>
            <!-- /wp:gutenverse/icon-list --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":29,"Mobile":null},"elementId":"guten-rFro5R","margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"15","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-rFro5R"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="rFro5R"><script>var toprFro5R = {"Desktop":{"point":"0","unit":"px"}};var bottomrFro5R = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-vYGdTN","color":{"r":255,"g":255,"b":255,"a":1},"typography":{"size":{"Desktop":{"point":"20","unit":"px"}},"font":{"label":"Roboto","value":"Roboto","type":"google"},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-vYGdTN">Useful Links</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/icon-list {"elementId":"guten-X9tiWP","spaceBetween":{"Desktop":"10"},"iconColor":{"r":252,"g":194,"b":54,"a":1},"textColor":{"r":255,"g":255,"b":255,"a":1},"textIndent":{"Desktop":"15"},"textTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300"}} -->
            <div class="guten-element guten-icon-list guten-X9tiWP"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-hYjBou"} -->
            <div class="guten-element guten-icon-list-item guten-hYjBou"><a id="guten-hYjBou"><i class="fas fa-angle-right"></i><span class="list-text ">Privacy Policy</span></a></div>
            <!-- /wp:gutenverse/icon-list-item -->
            
            <!-- wp:gutenverse/icon-list-item {"elementId":"guten-WORaPV"} -->
            <div class="guten-element guten-icon-list-item guten-WORaPV"><a id="guten-WORaPV"><i class="fas fa-angle-right"></i><span class="list-text ">Terms and Conditions</span></a></div>
            <!-- /wp:gutenverse/icon-list-item -->
            
            <!-- wp:gutenverse/icon-list-item {"elementId":"guten-GlXy8H"} -->
            <div class="guten-element guten-icon-list-item guten-GlXy8H"><a id="guten-GlXy8H"><i class="fas fa-angle-right"></i><span class="list-text ">Disclaimer</span></a></div>
            <!-- /wp:gutenverse/icon-list-item -->
            
            <!-- wp:gutenverse/icon-list-item {"elementId":"guten-HoElCL"} -->
            <div class="guten-element guten-icon-list-item guten-HoElCL"><a id="guten-HoElCL"><i class="fas fa-angle-right"></i><span class="list-text ">Support</span></a></div>
            <!-- /wp:gutenverse/icon-list-item --></div>
            <!-- /wp:gutenverse/icon-list --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":100,"Mobile":null},"elementId":"guten-th1LlA","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-th1LlA"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="th1LlA"><script>var topth1LlA = {"Desktop":{"point":"0","unit":"px"}};var bottomth1LlA = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-thLJz3","textAlign":{"Tablet":"center","Mobile":"left"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"size":{"Desktop":{"point":"20","unit":"px"}},"font":{"label":"Roboto","value":"Roboto","type":"google"},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-thLJz3">News Letter</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-oTlIVu","alignment":{"Tablet":"center","Mobile":"left"},"textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element gutenverse-text-editor guten-oTlIVu"><div class="text-content-inner"><!-- wp:paragraph {"textColor":"white"} -->
            <p class="has-white-color has-text-color">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-e5CQS1","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
            <div class="section-wrapper" data-id="e5CQS1"><script>var tope5CQS1 = {"Desktop":{"point":"0","unit":"px"}};var bottome5CQS1 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-e5CQS1 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-FvJaFv","horizontalAlign":{"Desktop":"default","Tablet":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"padding":{"Tablet":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-FvJaFv"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="FvJaFv"><script>var topFvJaFv = {"Desktop":{"point":"0","unit":"px"}};var bottomFvJaFv = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/form-builder {"elementId":"guten-jM4oCc","formId":{"label":"Form Subscribe","value":542},"hideAfterSubmit":false,"redirectTo":"","background":{"type":"default","color":""},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
            <form style="display:none" class="guten-element guten-form-builder guten-jM4oCc" data-form-id="542" data-hide-after="false" data-redirect=""><!-- wp:gutenverse/form-input-email {"elementId":"guten-1QxYrV","showLabel":false,"showHelper":false,"position":"left","labelColor":{"Desktop":{}},"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"helperColor":{"Desktop":{}},"helperPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"warningColor":{"Desktop":{}},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"75"},"Tablet":{"unit":"%","point":"90"},"Mobile":{"unit":"%","point":"75"}},"background":{"type":"default","color":""},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{"unit":"px","dimension":{"left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"0"}}},"inputPlaceholder":"Your Email Address","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"20","bottom":"18","left":"20"}},"Tablet":{"unit":"px","dimension":{"right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"left":"","right":""}}},"placeholderColor":{"Desktop":{}},"inputTypography":{"size":{"Desktop":{"point":"14","unit":"px"}},"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"}},"inputColorNormal":{"Desktop":{}},"inputBorderNormal":{"all":{"type":"none"},"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}}},"inputColorHover":{"Desktop":{}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputBorderFocus":{"radius":{"Desktop":{}}},"inputBgColorNormal":{"Desktop":{"r":255,"g":255,"b":255,"a":1}}} -->
            <div class="guten-element guten-form-input-email guten-form-input guten-input-position-left guten-1QxYrV hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email Address" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
            <!-- /wp:gutenverse/form-input-email -->
            
            <!-- wp:gutenverse/form-input-submit {"elementId":"guten-ROVLbr","content":"Send","buttonWidth":{"Desktop":""},"buttonBackground":{"type":"default","color":{"r":252,"g":194,"b":54,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":68,"g":68,"b":68,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"positioningType":{"Desktop":"inline"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"-5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"color":{"r":51,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"500"},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"22","right":"20","bottom":"21","left":"20"}},"Tablet":{},"Mobile":{}}} -->
            <div class="guten-element guten-button-wrapper guten-submit-wrapper guten-ROVLbr"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Send</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
            <!-- /wp:gutenverse/form-input-submit --></form>
            <!-- /wp:gutenverse/form-builder --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->
            
            <!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-ob9UeO","verticalAlign":"center","border":{"radius":{"Desktop":{"unit":"px"}},"top":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":0.1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"60","left":"","right":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"10","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}},"Tablet":{}}} -->
            <div class="section-wrapper" data-id="ob9UeO"><script>var topob9UeO = {"Desktop":{"point":"0","unit":"px"}};var bottomob9UeO = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-ob9UeO layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-iKOdkB","verticalAlign":{"Desktop":"default","Tablet":"default","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-iKOdkB"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="iKOdkB"><script>var topiKOdkB = {"Desktop":{"point":"0","unit":"px"}};var bottomiKOdkB = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-icotpe","alignment":{"Desktop":"left","Tablet":"left","Mobile":"center"},"textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
            <div class="guten-element gutenverse-text-editor guten-icotpe"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Copyright © 2022. All Right Reserved.</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-5ZdO9z","verticalAlign":{"Desktop":"default","Tablet":"default","Mobile":"default"}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-5ZdO9z"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="5ZdO9z"><script>var top5ZdO9z = {"Desktop":{"point":"0","unit":"px"}};var bottom5ZdO9z = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-zEnlzy","alignment":{"Desktop":"right","Tablet":"right","Mobile":"center"},"textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
            <div class="guten-element gutenverse-text-editor guten-zEnlzy"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Construction &amp; Real Estate by Jegstudio.</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
