<?php
/**
 * Gutenverse About Us Why content.
 */
return array(
	'title'      => __( 'Gutenverse About Us Why', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"gap":"no","elementId":"guten-5e9nnt","verticalAlign":"center","background":{"type":"default","color":""},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"left":"10","right":"10","top":"60","bottom":"60"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","left":"10","right":"10"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
			<div class="section-wrapper" data-id="5e9nnt"><script>var top5e9nnt = {"Desktop":{"point":"0","unit":"px"}};var bottom5e9nnt = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-5e9nnt layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":51.4,"Tablet":100,"Mobile":null},"elementId":"guten-hm22ZI","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"60","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"left":"","top":"20","right":"","bottom":""}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-hm22ZI"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="hm22ZI"><script>var tophm22ZI = {"Desktop":{"point":"0","unit":"px"}};var bottomhm22ZI = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-2W1hqH","textAlign":{"Mobile":"center"},"color":{"r":51,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"spacing":{"Desktop":""},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"0"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-2W1hqH animated guten-element-hide desktop-fadeInLeft">Why Choose Us</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-wb6sWe","alignment":{"Mobile":"center"},"textColor":{"r":68,"g":68,"b":68,"a":1},"typography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"80"}} -->
			<div class="guten-element gutenverse-text-editor guten-wb6sWe animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem aperiam</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-izGD1I","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Tablet":{"unit":"px","dimension":{"bottom":"35"}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
			<div class="section-wrapper" data-id="izGD1I"><script>var topizGD1I = {"Desktop":{"point":"0","unit":"px"}};var bottomizGD1I = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-izGD1I layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-cae7WS","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20","bottom":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-cae7WS"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="cae7WS"><script>var topcae7WS = {"Desktop":{"point":"0","unit":"px"}};var bottomcae7WS = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-Yozt5j","title":"Speed Builder","titleTag":"h3","description":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant doloremque laudantium totam rem aperiam","icon":"gtn gtn-clock11-light","iconPosition":"left","align":{"Desktop":"left","Mobile":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"10","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"iconColor":{"r":252,"g":194,"b":54,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"all":{"type":"solid","width":"1","color":{"r":252,"g":194,"b":54,"a":1}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Mobile":[]},"titleColor":{"r":51,"g":51,"b":51,"a":1},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"r":68,"g":68,"b":68,"a":1},"descTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"240"}} -->
			<div class="guten-element guten-Yozt5j animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-clock11-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Speed Builder</h3><p class="icon-box-description">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant doloremque laudantium totam rem aperiam</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":-100,"Mobile":null},"elementId":"guten-vxeXGf","margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","right":"20","bottom":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-vxeXGf"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vxeXGf"><script>var topvxeXGf = {"Desktop":{"point":"0","unit":"px"}};var bottomvxeXGf = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-oP42hc","title":"Professional","titleTag":"h3","description":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant doloremque laudantium totam rem aperiam","icon":"gtn gtn-team-2-line","iconPosition":"left","align":{"Desktop":"left","Mobile":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"10","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"iconColor":{"r":252,"g":194,"b":54,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"all":{"type":"solid","width":"1","color":{"r":252,"g":194,"b":54,"a":1}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Mobile":[]},"titleColor":{"r":51,"g":51,"b":51,"a":1},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"r":68,"g":68,"b":68,"a":1},"descTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"320"}} -->
			<div class="guten-element guten-oP42hc animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-team-2-line"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Professional</h3><p class="icon-box-description">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant doloremque laudantium totam rem aperiam</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-1jCgZr","margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-1jCgZr"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="1jCgZr"><script>var top1jCgZr = {"Desktop":{"point":"0","unit":"px"}};var bottom1jCgZr = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-1sUPMD","title":"24/7 Support","titleTag":"h3","description":"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant doloremque laudantium totam rem aperiam","icon":"gtn gtn-customer-support-2-light","iconPosition":"left","align":{"Desktop":"left","Mobile":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}}},"iconColor":{"r":252,"g":194,"b":54,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"all":{"type":"solid","width":"1","color":{"r":252,"g":194,"b":54,"a":1}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Mobile":[]},"titleColor":{"r":51,"g":51,"b":51,"a":1},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"r":68,"g":68,"b":68,"a":1},"descTypography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
			<div class="guten-element guten-1sUPMD animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-customer-support-2-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">24/7 Support</h3><p class="icon-box-description">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusant doloremque laudantium totam rem aperiam</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":48.6,"Tablet":91,"Mobile":null},"elementId":"guten-LLkRjW","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"},"hideMobile":true} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-LLkRjW animated guten-element-hide desktop-fadeInRight hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LLkRjW"><script>var topLLkRjW = {"Desktop":{"point":"0","unit":"px"}};var bottomLLkRjW = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-2mi8MV","imgSrc":{"media":{"imageId":180,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/safety-health-worker-engineer-construction-industry-1575605-pxhere.com-150x150.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/safety-health-worker-engineer-construction-industry-1575605-pxhere.com-300x200.webp","orientation":"landscape"},"large":{"height":683,"width":1024,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/safety-health-worker-engineer-construction-industry-1575605-pxhere.com-1024x683.webp","orientation":"landscape"},"full":{"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/safety-health-worker-engineer-construction-industry-1575605-pxhere.com.webp","height":1280,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","imgBorder":{"radius":{"Desktop":[],"Tablet":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"70","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"positioningLocation":"default","positioningLeft":{"Desktop":{"point":"","unit":"px"}},"positioningRight":{"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"point":"","unit":"px"}},"positioningBottom":{"Desktop":{"unit":"%","point":""}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-2mi8MV"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( RENOVATER_URI ) . 'assets/img/safety-health-worker-engineer-construction-industry-1575605-pxhere.com.webp" height="1280" width="1920"/></a></div>
			<!-- /wp:gutenverse/image -->
			
			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-RD0u9u","margin":{"Desktop":{"unit":"%","dimension":{"top":"-78","right":"-10","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
			<div class="section-wrapper" data-id="RD0u9u"><script>var topRD0u9u = {"Desktop":{"point":"0","unit":"px"}};var bottomRD0u9u = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-RD0u9u layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-2LYpft","border":{"radius":{"Desktop":[]},"all":{"type":"solid","color":{"r":252,"g":194,"b":54,"a":1},"width":"30"}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"","right":"0","left":"8","bottom":"0"}}},"padding":{"Desktop":[]}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-2LYpft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="2LYpft"><script>var top2LYpft = {"Desktop":{"point":"0","unit":"px"}};var bottom2LYpft = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-eP9olx","space":{"Desktop":{"point":"340","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
			<div class="guten-element guten-spacer guten-eP9olx"></div>
			<!-- /wp:gutenverse/spacer --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
