<?php
/**
 * Gutenverse Home Fun Fact content.
 */
return array(
	'title'      => __( 'Gutenverse Home Fun Fact', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"elementId":"guten-RbNAVf","background":{"type":"default","image":{"Desktop":{"id":552,"image":"' . esc_url( RENOVATER_URI ) . 'assets/img/man-working-sky-roof-wall-asphalt-1139579-pxhere.com.webp"}},"position":{"Desktop":"center right"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(239, 170, 6, 1)","opacity":1,"active":true,"id":1,"offset":"0.161"},{"color":"rgba(0, 0, 0, 0.71)","active":false,"opacity":0.71,"id":2,"offset":"0.161"}],"gradientType":"linear","gradientAngle":"300"},"opacity":"","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"50","top":"50"}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10","top":"30","bottom":"30"}}}} -->
			<div class="section-wrapper" data-id="RbNAVf"><script>var topRbNAVf = {"Desktop":{"point":"0","unit":"px"}};var bottomRbNAVf = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-RbNAVf layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":56.01,"Tablet":100},"elementId":"guten-cfJMek","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-cfJMek"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="cfJMek"><script>var topcfJMek = {"Desktop":{"point":"0","unit":"px"}};var bottomcfJMek = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-B4djhT","textAlign":{"Mobile":"center","Tablet":"left"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"600"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"0"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-B4djhT animated guten-element-hide desktop-fadeInLeft">Awesome Facts</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-hb1THh","alignment":{"Mobile":"center","Tablet":"left"},"typography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Mobile":{"unit":"em","point":"1.6"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"60","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"delay":"150","duration":"normal"}} -->
			<div class="guten-element gutenverse-text-editor guten-hb1THh animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph {"textColor":"white"} -->
			<p class="has-white-color has-text-color">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo perspiciatis unde omnis iste.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"isChild":true,"gap":"no","elementId":"guten-ZWpwTs","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"140","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="section-wrapper" data-id="ZWpwTs"><script>var topZWpwTs = {"Desktop":{"point":"0","unit":"px"}};var bottomZWpwTs = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-ZWpwTs layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-2DFQrt","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"0"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-2DFQrt"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="2DFQrt"><script>var top2DFQrt = {"Desktop":{"point":"0","unit":"px"}};var bottom2DFQrt = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-0GjeK6","icon":"gtn gtn-deal-light","iconColor":{"Desktop":{"r":252,"g":194,"b":54,"a":1}},"iconBorder":{"radius":{"Desktop":[],"Tablet":[]}},"iconSize":{"Desktop":"","Tablet":""},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"prefix":"","number":"200","suffix":"+","title":"Completed Projects","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"numberBottomSpace":{"Desktop":""},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"0"}} -->
			<div class="guten-element guten-0GjeK6 animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-deal-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="200" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Completed Projects</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"elementId":"guten-QOn9VZ","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"80"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-QOn9VZ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="QOn9VZ"><script>var topQOn9VZ = {"Desktop":{"point":"0","unit":"px"}};var bottomQOn9VZ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-RBBBCR","icon":"gtn gtn-User-light","iconColor":{"Desktop":{"r":252,"g":194,"b":54,"a":1}},"iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"prefix":"","number":"300","suffix":"+","title":"Happy Client","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"contentPadding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"30","left":"30","top":"","bottom":""}}},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"150"}} -->
			<div class="guten-element guten-RBBBCR animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-User-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="300" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Happy Client</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"elementId":"guten-nuCbWo","animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-nuCbWo"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="nuCbWo"><script>var topnuCbWo = {"Desktop":{"point":"0","unit":"px"}};var bottomnuCbWo = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-UP9CQ0","icon":"gtn gtn-team-2-line","iconColor":{"Desktop":{"r":252,"g":194,"b":54,"a":1}},"iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"prefix":"","number":"128","suffix":"","title":"Professional Team","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"contentPadding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<div class="guten-element guten-UP9CQ0 animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-team-2-line"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="128" data-duration="3500"></span><span class="suffix"></span></div><span class="title">Professional Team</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50},"elementId":"guten-RCCMf7","animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"320"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-RCCMf7"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="RCCMf7"><script>var topRCCMf7 = {"Desktop":{"point":"0","unit":"px"}};var bottomRCCMf7 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-f7Ee9j","icon":"gtn gtn-trophy-light","iconColor":{"Desktop":{"r":252,"g":194,"b":54,"a":1}},"iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"prefix":"","number":"110","suffix":"","title":"Awards Winning","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleTypography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300"},"contentPadding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"30","left":"30"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"350"}} -->
			<div class="guten-element guten-f7Ee9j animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-trophy-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="110" data-duration="3500"></span><span class="suffix"></span></div><span class="title">Awards Winning</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":43.99,"Tablet":30,"Mobile":null},"elementId":"guten-bWMmGu","margin":{"Mobile":[]},"padding":{"Mobile":[]},"hideTablet":true,"hideMobile":true} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-bWMmGu hide-tablet hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="bWMmGu"><script>var topbWMmGu = {"Desktop":{"point":"0","unit":"px"}};var bottombWMmGu = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
