<?php
/**
 * Gutenverse Home Client Logo content.
 */
return array(
	'title'      => __( 'Gutenverse Home Client Logo', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"gap":"no","elementId":"guten-OI1DiP","verticalAlign":"center","background":{"type":"default","color":{"r":239,"g":239,"b":239,"a":1}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"40","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}}} -->
			<div class="section-wrapper" data-id="OI1DiP"><script>var topOI1DiP = {"Desktop":{"point":"0","unit":"px"}};var bottomOI1DiP = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-OI1DiP layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-KbZEoK","verticalAlign":{"Desktop":"default","Tablet":"default"},"horizontalAlign":{"Desktop":"default","Tablet":"default"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-KbZEoK"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KbZEoK"><script>var topKbZEoK = {"Desktop":{"point":"0","unit":"px"}};var bottomKbZEoK = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-K8vns0","imgSrc":{"media":{"imageId":1800,"sizes":{"thumbnail":{"height":95,"width":150,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-1-150x95.webp","orientation":"landscape"},"medium":{"height":61,"width":300,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-1-300x61.webp","orientation":"landscape"},"full":{"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-1.webp","height":95,"width":471,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":[],"Mobile":[]}},"opacity":"0.5","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"0"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"70","bottom":"","left":"70"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-K8vns0 animated guten-element-hide desktop-fadeInUp"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-1.webp" height="95" width="471"/></a></div>
			<!-- /wp:gutenverse/image --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-iAnJTM","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-iAnJTM"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="iAnJTM"><script>var topiAnJTM = {"Desktop":{"point":"0","unit":"px"}};var bottomiAnJTM = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-nkb0oS","imgSrc":{"media":{"imageId":1801,"sizes":{"thumbnail":{"height":102,"width":150,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-3-150x102.webp","orientation":"landscape"},"medium":{"height":50,"width":300,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-3-300x50.webp","orientation":"landscape"},"full":{"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-3.webp","height":102,"width":615,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":[],"Mobile":[]}},"opacity":"0.5","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"70","bottom":"","left":"70"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-nkb0oS animated guten-element-hide desktop-fadeInUp"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-3.webp" height="102" width="615"/></a></div>
			<!-- /wp:gutenverse/image --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-CwAQWF","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-CwAQWF"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="CwAQWF"><script>var topCwAQWF = {"Desktop":{"point":"0","unit":"px"}};var bottomCwAQWF = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-qe0PWV","imgSrc":{"media":{"imageId":1802,"sizes":{"thumbnail":{"height":118,"width":150,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-2.webp-150x118.webp","orientation":"landscape"},"medium":{"height":68,"width":300,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-2.webp-300x68.webp","orientation":"landscape"},"full":{"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-2.webp","height":118,"width":519,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":[],"Mobile":[]}},"opacity":"0.5","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"70","bottom":"","left":"70"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"30","bottom":"30","left":"30"}}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-qe0PWV animated guten-element-hide desktop-fadeInUp"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-2.webp" height="118" width="519"/></a></div>
			<!-- /wp:gutenverse/image --></div></div></div>
			<!-- /wp:gutenverse/column -->
			
			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-0Vpep2","margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"240"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-0Vpep2"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="0Vpep2"><script>var top0Vpep2 = {"Desktop":{"point":"0","unit":"px"}};var bottom0Vpep2 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-5eIlwP","imgSrc":{"media":{"imageId":1803,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-4-150x150.webp","orientation":"landscape"},"medium":{"height":72,"width":300,"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-4-300x72.webp","orientation":"landscape"},"full":{"url":"' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-4.webp","height":161,"width":668,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":[],"Mobile":[]}},"opacity":"0.5","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"70","bottom":"","left":"70"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"30","bottom":"30","left":"30"}}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-5eIlwP animated guten-element-hide desktop-fadeInUp"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( RENOVATER_URI ) . 'assets/img/logo-partner-4.webp" height="161" width="668"/></a></div>
			<!-- /wp:gutenverse/image --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
