<?php
/**
 * Gutenverse FAQ Call to Action content.
 */
return array(
	'title'      => __( 'Gutenverse FAQ Call to Action', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"elementId":"guten-OqBJa3","background":{"type":"default","image":{"Desktop":{"id":342,"image":"' . esc_url( RENOVATER_URI ) . 'assets/img/writing-hand-architecture-architect-construction-pattern-701875-pxhere.com.webp"}},"position":{"Desktop":"center right"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"yposition":{"Desktop":{"point":"","unit":"px"}},"xposition":{"Desktop":{"point":"","unit":"px"}}},"backgroundOverlay":{"type":"default","color":{"r":7,"g":7,"b":7,"a":1}},"opacity":"0.8","margin":{"Desktop":[],"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","left":"10","right":"10"}},"Tablet":{"unit":"px","dimension":{"top":"60","right":"20","bottom":"60","left":"20"}}}} -->
			<div class="section-wrapper" data-id="OqBJa3"><script>var topOqBJa3 = {"Desktop":{"point":"0","unit":"px"}};var bottomOqBJa3 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-OqBJa3 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-PF1k7w","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-PF1k7w"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="PF1k7w"><script>var topPF1k7w = {"Desktop":{"point":"0","unit":"px"}};var bottomPF1k7w = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-OBWF5r","textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"38","unit":"px"},"Mobile":{"point":"24","unit":"px"},"Tablet":{"point":"32","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"0"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-OBWF5r animated guten-element-hide desktop-fadeInUp">Are You Ready To Build New Project With Us?</h2>
			<!-- /wp:gutenverse/heading -->
			
			<!-- wp:gutenverse/text-editor {"elementId":"guten-2ST0Pm","alignment":{"Desktop":"center","Tablet":"center","Mobile":"center"},"textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Mobile":{"unit":"em","point":"1.6"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"","right":"23","bottom":"","left":"23"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"5","bottom":"0","left":"5"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"150"}} -->
			<div class="guten-element gutenverse-text-editor guten-2ST0Pm animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis&nbsp;</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->
			
			<!-- wp:gutenverse/button {"elementId":"guten-W19JFe","content":"Contact Us","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}}},"buttonBackground":{"type":"default","color":{"r":252,"g":194,"b":54,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"},"color":{"r":51,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"transform":"default","spacing":{"Desktop":""},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"500"},"hoverTextColor":{"r":51,"g":51,"b":51,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-W19JFe"><a class="guten-button animated guten-element-hide desktop-fadeInUp guten-button-sm" href="#"><span>Contact Us</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
